Batch:

  customers:
      not_null:  [customer_id, segment_id, phone, gender, region_id, signup_date]

      data_types:
        customer_id:  pl.Int64
        full_name:  pl.Utf8
        email:  pl.Utf8
        phone:  pl.Utf8
        region_id:  pl.Int64
        segment_id: pl.Int64
        signup_date:  pl.Date
        gender: pl.Utf8
        created_at: pl.Timestamp
        updated_at: pl.Timestamp

      unique:    [customer_id]
      regex:
        email: '^[^@\s]+@[^@\s]+\.[^@\s]+$'
        phone: '^1[0-25][0-9]{8}$'

      allowed_values:
        gender: [male, female]

      foreign_keys:
        region_id:  regions.region_id
        segment_id: segments.segment_id

  drivers:
    not_null: [driver_id, shift, vehicle_type, region_id, national_id, hire_date, rating_avg, on_time_rate, cancel_rate, completed_deliveries, is_active]

    data_types:
      driver_id:  pl.Int64
      driver_name:  pl.Utf8
      driver_phone: pl.Utf8
      national_id:  pl.Utf8
      region_id:  pl.Int64
      shift:  pl.Utf8
      vehicle_type: pl.Utf8
      hire_date:  pl.Date
      rating_avg: pl.Decimal
      on_time_rate: pl.Decimal
      cancel_rate:  pl.Decimal
      completed_deliveries: pl.Int64
      is_active:  pl.Boolean
      created_at: pl.Timestamp
      updated_at: pl.Timestamp

    unique:   [driver_id, national_id]
    range:
      rating_avg:   [1.0, 5.0]
      on_time_rate: [0.0, 1.0]
      cancel_rate:  [0.0, 1.0]
      completed_deliveries: [0, INF]
    allowed_values:
      shift:        [morning, evening, night]
      vehicle_type: [bike, motorbike, car]
    regex:
      driver_phone: '^01[0-25][0-9]{8}$'
      national_id: '^[2-3][0-9]{13}$'
    foreign_keys:
      region_id: regions.region_id

  restaurants:
    not_null: [restaurant_id, restaurant_name, region_id, category_id, price_tier, is_active, rating_avg, prep_time_avg_min]

    data_types:
      restaurant_id:  pl.Int64
      restaurant_name:  pl.Utf8
      region_id:  pl.Int64
      category_id:  pl.Int64
      price_tier: pl.Utf8
      rating_avg: pl.Decimal
      prep_time_avg_min:  pl.Int64
      is_active:  pl.Boolean
      created_at: pl.Timestamp
      updated_at: pl.Timestamp

    unique:   [restaurant_id]
    range:
      rating_avg: [1.0, 5.0]
      prep_time_avg_min: [0, INF]
    allowed_values:
      price_tier: [Low, Mid, High]
    foreign_keys:
      region_id:   regions.region_id
      category_id: categories.category_id

  agents:
    not_null: [agent_id, agent_phone, skill_level, team_id, is_active, hire_date, avg_handle_time_min, resolution_rate, csat_score]
    
    data_types:
      agent_id: pl.Int64
      agent_name: pl.Utf8
      agent_email:  pl.Utf8
      agent_phone:  pl.Utf8
      team_id:  pl.Int64
      skill_level:  pl.Utf8
      hire_date:  pl.Date
      avg_handle_time_min:  pl.Int64
      resolution_rate:  pl.Decimal
      csat_score: pl.Decimal
      is_active:  pl.Boolean
      created_at: pl.Timestamp
      updated_at: pl.Timestamp


    unique:   [agent_id]

    range:
      avg_handle_time_min: [0, INF]
      resolution_rate: [0.0, 1.0]
      csat_score: [0.0, 5.0]

    allowed_values:
      skill_level: [Junior, Mid, Senior, Lead]

    regex:
      agent_email: '^[^@\s]+@[^@\s]+\.[^@\s]+$'
      agent_phone: '^[0-9]{10}$' # It starts with 1

    foreign_keys:
      team_id: teams.team_id

  cities:
    not_null: [city_id, city_name, country, timezone]
    unique: [city_id]
    data_types:
      city_id:  pl.Int64
      city_name:  pl.Utf8
      country:  pl.Utf8
      timezone: pl.Utf8
      
  regions:
    not_null: [region_id, region_name, city_id, delivery_base_fee]
    unique: [region_id]
    data_types:
      region_id: pl.Int64
      region_name: pl.Utf8
      city_id: pl.Int64
      delivery_base_fee: pl.Decimal
    range:
      delivery_base_fee: [0.0, 200]
    foreign_keys:
      city_id: cities.city_id

  categories:
    not_null: [category_id, category_name]
    unique: [category_id]
    data_types:
      category_id: pl.Int64
      category_name: pl.Utf8

  reason_categories:
    not_null: [reason_category_id, category_name]
    unique: [reason_category_id]
    data_types:
      reason_category_id: pl.Int64
      category_name: pl.Utf8

  reasons:
    not_null: [reason_id, reason_name, reason_category_id, severity_level, typical_refund_pct]
    unique: [reason_id]
    data_types:
      reason_id: pl.Int64
      reason_name: pl.Utf8
      reason_category_id: pl.Int64
      severity_level: pl.Int64
      typical_refund_pct: pl.Decimal
    range:
      severity_level: [1, 5]
      typical_refund_pct: [0.0, 1.0]
    foreign_keys:
      reason_category_id: reason_categories.reason_category_id

  segments:
    not_null: [segment_id, segment_name, discount_pct, priority_support]
    unique: [segment_id]
    data_types:
      segment_id: pl.Int64
      segment_name: pl.Utf8
      discount_pct: pl.Int64
      priority_support: pl.Boolean

    range:
      discount_pct: [0, 100]

  teams:
    not_null: [team_id, team_name]
    unique: [team_id]
    data_types:
      team_id: pl.Int64
      team_name: pl.Utf8

  channels:
    not_null: [channel_id, channel_name]
    unique: [channel_id]
    data_types:
      channel_id: pl.Int64
      channel_name: pl.Utf8

  priorities:
    not_null: [priority_id, priority_code, priority_name, sla_first_response_min, sla_resolution_min]
    unique: [priority_id]
    data_types:
      priority_id: pl.Int64
      priority_code:  pl.Utf8
      priority_name:  pl.Utf8
      sla_first_response_min: pl.Int64
      sla_resolution_min: pl.Int64
    range:
      sla_first_response_min: [0, 1440]
      sla_resolution_min: [0, 1440]


Stream:

  orders:
    not_null: [order_id, customer_id, restaurant_id, driver_id, region_id, order_status, payment_method, order_amount, delivery_fee, discount_amount, total_amount, order_created_at, delivered_at]
    
    data_types:
      order_id: pl.Utf8
      customer_id: pl.Int64
      restaurant_id: pl.Int64
      driver_id: pl.Int64
      region_id: pl.Int64
      order_amount: pl.Decimal
      delivery_fee: pl.Decimal
      discount_amount: pl.Decimal
      total_amount: pl.Decimal
      order_status: pl.Utf8
      payment_method: pl.Utf8
      order_created_at: pl.Timestamp
      delivered_at: pl.Timestamp
    
    unique:   [order_id]
    range:
      order_amount:    [0.01, 10000]
      delivery_fee:    [0.0,  500]
      discount_amount: [0.0,  500]
      total_amount:    [0.01, 10000]
    allowed_values:
      order_status:   [Delivered, Cancelled, Refunded]
      payment_method: [card, cash, wallet]
    foreign_keys:
      customer_id:   customers.customer_id
      restaurant_id: restaurants.restaurant_id
      driver_id:     drivers.driver_id
      region_id:     regions.region_id

  tickets:
    not_null: [ticket_id, order_id, customer_id, agent_id, reason_id, priority_id, channel_id, status, created_at]
    
    data_types:
      ticket_id: pl.Utf8
      order_id: pl.Utf8
      customer_id: pl.Int64
      driver_id: pl.Int64
      restaurant_id: pl.Int64
      agent_id: pl.Int64
      reason_id: pl.Int64
      priority_id: pl.Int64
      channel_id: pl.Int64
      status: pl.Utf8
      refund_amount: pl.Decimal
      created_at: pl.Timestamp
      first_response_at: pl.Timestamp
      resolved_at: pl.Timestamp
      sla_first_due_at: pl.Timestamp
      sla_resolve_due_at: pl.Timestamp
    
    unique:   [ticket_id]
    allowed_values:
      status: [Open, InProgress, Resolved, Closed, Reopened]
    range:
      refund_amount: [0.0, 10000]
    foreign_keys:
      order_id:    orders.order_id
      customer_id: customers.customer_id
      agent_id:    agents.agent_id
      reason_id:   reasons.reason_id
      priority_id: priorities.priority_id
      channel_id:  channels.channel_id

  ticket_events:
    not_null: [event_id, ticket_id, agent_id, event_ts, new_status]
    
    data_types:
      event_id: pl.Utf8
      ticket_id: pl.Utf8
      agent_id: pl.Int64
      event_ts: pl.Timestamp
      old_status: pl.Utf8
      new_status: pl.Utf8
      notes: pl.Utf8
    
    unique: [event_id]
    allowed_values:
      new_status: [Open, InProgress, Resolved, Closed, Reopened]
    foreign_keys:
      ticket_id: tickets.ticket_id
      agent_id:  agents.agent_id